name: Creates a docker image for production

on: [pull_request]
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Publish image to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: luizae
          PASSWORD: ${{ secrets.GH_TOKEN }}
          REGISTRY: 'docker.pkg.github.com'
          DOCKERFILE: 'Dockerfile'
          IMAGE_NAME: 'tindev'
          TAG_NAME: 'qa'
          LATEST: 'true'