name: Test and generate the docker image

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting and testing with nodejs 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - run: npm install
      - run: npm run test:ci
      - run: npm run build
      - run: npm run build
  docker_publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Publish image to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: luizae
          PASSWORD: ${{ secrets.GH_TOKEN }}
          REGISTRY: 'docker.pkg.github.com'
          DOCKERFILE: 'Dockerfile'
          IMAGE_NAME: 'tindev'
          TAG_NAME: 'qa'
          LATEST: 'true'
